server:
  port: 9999

spring:
  application:
    name: course-online-selling
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /v3/api-docs

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 20
  refreshable-duration: 120