server:
  port: 9999

spring:
  application:
    name: course-online-selling
  profiles:
    active: prod

springdoc:
  api-docs:
    path: /v3/api-docs

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 7200

payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "HUWJVPVM"
    secretKey: "JTQDOZVNOADCXAQDJTKVQDJXOPTJTPLF"
    returnUrl: "http://127.0.0.1:3000/Frontend/pages/Process_Payment/Process_Payment.html"
    version: "2.1.0"
    command: "pay"
    orderType: "other"