spring:
  datasource:
      url: ${PROD_JDBC_DATABASE_URL}
      username: ${PROD_JDBC_DATABASE_USERNAME}
      password: ${PROD_JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update